### ISSUE TITLE
Speed up the quantization of data 

### ISSUE THREAD

**Issue by nishantthakur** [cgorman/tensorflow-som#6]
Thanks for building this package, 
Using your package, I have learned weight matrix for SOM. Now, I need to do quantization (assign the learned weights) of all the data points (~500 million) used for training and as well as new data points based on learned SOM model. Is there any faster way (batch processing) rather than looping on each data point and assigning the "Best Matching Units"? Looping takes forever for quantization.

Thanks

**Comment by cgorman** [comment]
If I'm understanding your question correctly, you may be able to reuse [this chunk of code](https://github.com/cgorman/tensorflow-som/blob/master/tf_som.py#L228-L244) for your goals. The output would be a list of 2D coordinates of the best matching neurons for an input batch. That would be the batch formulation for getting the best matching units, and since it's only a few operations I think you could use a very large batch size. All you would need to compute this is the SOM weight matrix, a batch of input vectors, and the `location_vects` tensor from the SOM class. 

If I misunderstood your question let me know!
